import './globals.css';
import { Chakra_Petch} from 'next/font/google';

const chakraPetch = Chakra_Petch({ subsets: ['latin'],weight:['300','400','500','600','700'] });

export const metadata = {
  title: 'YASH SINGH-Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={chakraPetch.className}>{children}</body>
    </html>
  )
}
